# Coleta de dados com Python
### Cotações de ações e ETFs

Instalando o Yahoo Finance

In [ ]:
!pip install yfinance

In [8]:
import yfinance as yf

### Baixando os dados do Yahoo Finance

In [16]:
lista_empresas = (['WEGE3.SA', 'PETR4.SA'])
dados_empresa = yf.download(lista_empresas, start ='2024-01-01')
dados_empresa

[*********************100%%**********************]  2 of 2 completed

Price       Adj Close                 Close                  High             \
Ticker       PETR4.SA   WEGE3.SA   PETR4.SA   WEGE3.SA   PETR4.SA   WEGE3.SA
Date
2024-01-02  37.779999  36.214455  37.779999  36.570000  37.889999  37.049999
2024-01-03  38.959999  36.491730  38.959999  36.849998  39.119999  37.290001
2024-01-04  38.630001  36.006496  38.630001  36.360001  39.349998  37.099998
2024-01-05  38.720001  35.620289  38.720001  35.970001  39.139999  36.349998
2024-01-08  38.430000  35.709412  38.430000  36.060001  38.430000  36.299999
...               ...        ...        ...        ...        ...        ...
2024-04-01  37.650002  37.990002  37.650002  37.990002  37.709999  38.340000
2024-04-02  38.619999  38.169998  38.619999  38.169998  38.650002  38.310001
2024-04-03  38.419998  37.889999  38.419998  37.889999  39.009998  38.459999
2024-04-04  37.980000  38.099998  37.980000  38.099998  39.480000  38.669998
2024-04-05  38.099998  37.990002  38.099998  37.990002  38.570000  38.200001

Price             Low                  Open                Volume
Ticker       PETR4.SA   WEGE3.SA   PETR4.SA   WEGE3.SA   PETR4.SA WEGE3.SA
Date
2024-01-02  37.400002  36.330002  37.439999  36.910000   24043800  3991200
2024-01-03  37.669998  36.380001  37.799999  36.380001   52300200  6435500
2024-01-04  38.509998  36.259998  39.119999  36.700001   45344900  5461100
2024-01-05  38.410000  35.570000  38.869999  36.029999   35783700  9274700
2024-01-08  37.610001  35.639999  38.380001  35.860001   35158100  3433300
...               ...        ...        ...        ...        ...      ...
2024-04-01  37.209999  37.570000  37.500000  38.200001   23697800  6335000
2024-04-02  37.770000  37.799999  37.820000  37.860001   45930700  5312400
2024-04-03  38.220001  37.680000  38.700001  38.220001   31437200  7117600
2024-04-04  37.430000  37.820000  38.470001  37.889999  165566800  4821600
2024-04-05  37.169998  37.820000  37.900002  37.919998   65409300  4476700

[66 rows x 12 columns]

### Dados do Fundamentus - Pegar os dados financeiros das empresas que operam na bolsa

#### Instalando Selenium, pricipal pacote de web-scrapping

In [18]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\home\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\home\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\home\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\home\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\home\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\home\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\home\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\home\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\home\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\home\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\home\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\home\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\home\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\home\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\home\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\home\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

#### Gerenciar driver com webdriver-manager

In [20]:
!pip install webdriver-manager

Collecting webdriver-manager
  Obtaining dependency information for webdriver-manager from https://files.pythonhosted.org/packages/b1/51/b5c11cf739ac4eecde611794a0ec9df420d0239d51e73bc19eb44f02b48b/webdriver_manager-4.0.1-py2.py3-none-any.whl.metadata
  Downloading webdriver_manager-4.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in c:\users\home\anaconda3\lib\site-packages (from webdriver-manager) (2.31.0)
Requirement already satisfied: python-dotenv in c:\users\home\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in c:\users\home\anaconda3\lib\site-packages (from webdriver-manager) (23.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\home\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\home\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\home\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\home\anaconda3\lib\site-packages (from requests->webdriver-manager) (2023.7.22)
Downloading webdriver_manager-4.0.1-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.1

#### Importando os pacotes

In [22]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

#### Criando robô para pegar os dados do site Fundamentus

In [29]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [30]:
url_site = 'https://www.fundamentus.com.br/resultado.php'

driver.get(url_site)

#### Pegando os dados da tabela pelo navegador

In [ ]:
local_tabela = '/html/body/div[1]/div[2]/table'

elemento = driver.find_element('xpath', local_tabela)
html_tabela = elemento.get_attribute('outerHTML')
html_tabela

#### Colocando os dados em uma tabela com o pandas

In [34]:
tabela = pd.read_html(str(html_tabela), thousands = '.', decimal = ',')[0]
tabela

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,MAPT3,6.00,-36.52,-0.88,0.000,"0,00%",7.133,-1102.80,-41.77,-0.79,...,-41.77,"0,00%","0,00%",0.00,"-17,19%","2,42%",4.549610e+03,-6.244000e+06,0.00,"0,00%"
1,MAPT4,5.00,-30.43,-0.74,0.000,"0,00%",5.944,-919.00,-34.81,-0.65,...,-34.81,"0,00%","0,00%",0.00,"-17,19%","2,42%",1.343060e+04,-6.244000e+06,0.00,"0,00%"
2,RHDS4,1.00,363.45,29.50,4.977,"0,00%",7.182,-593.56,68.11,-24.55,...,53.72,"7,31%","1,17%",0.97,"11,80%","8,12%",0.000000e+00,2.720450e+08,1.49,"4,38%"
3,EBTP3,10.21,-43.56,1.17,0.548,"0,00%",0.353,-502.47,6.42,-0.73,...,2.85,"8,53%","-1,03%",0.99,"6,03%","-2,68%",0.000000e+00,1.078220e+10,0.39,"22,10%"
4,EBTP4,10.00,-42.66,1.14,0.537,"0,00%",0.346,-492.13,6.29,-0.71,...,2.81,"8,53%","-1,03%",0.99,"6,03%","-2,68%",0.000000e+00,1.078220e+10,0.39,"22,10%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,UOLL4,19.62,43.52,2.35,2.054,"0,00%",1.403,457.14,15.14,-12.83,...,16.49,"13,56%","4,69%",1.01,"10,57%","5,40%",0.000000e+00,1.003690e+09,0.23,"21,99%"
982,CXSE3,15.64,13.10,3.73,0.000,"6,46%",3.350,949.34,-426.41,1016.55,...,-418.66,"0,00%","0,00%",1.03,"-0,84%","28,46%",1.054240e+08,1.258590e+10,0.00,"0,00%"
983,TIET11,17.44,6.09,3.13,3.010,"0,00%",0.638,1434.52,5.02,-1.05,...,6.62,"59,93%","49,91%",1.00,"13,97%","51,45%",0.000000e+00,2.222740e+09,2.67,"7,76%"
984,TIET3,3.49,6.09,3.13,3.012,"0,00%",0.638,1435.34,5.03,-1.05,...,6.63,"59,93%","49,91%",1.00,"13,97%","51,45%",0.000000e+00,2.222740e+09,2.67,"7,76%"
985,TIET4,3.51,6.13,3.15,3.029,"0,00%",0.642,1443.57,5.06,-1.05,...,6.65,"59,93%","49,91%",1.00,"13,97%","51,45%",0.000000e+00,2.222740e+09,2.67,"7,76%"

#### Fechando o navegador

In [37]:
driver.quit()

#### Dados de Criptomoedas - com pacote cryptocmd
https://coinmarketcap.com/pt-br/

In [38]:
!pip install cryptocmd

Collecting cryptocmd
  Obtaining dependency information for cryptocmd from https://files.pythonhosted.org/packages/d6/60/ecf5636cd124e089033cede8d39d4ef842f5445ddf4ead19d49f5757be74/cryptocmd-0.6.4-py3-none-any.whl.metadata
  Downloading cryptocmd-0.6.4-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: requests in c:\users\home\anaconda3\lib\site-packages (from cryptocmd) (2.31.0)
Collecting tablib (from cryptocmd)
  Obtaining dependency information for tablib from https://files.pythonhosted.org/packages/ff/d0/30af53e5ae2c4cb27aa114c1af1f1aa21709159a2516d7b2380dca31483f/tablib-3.6.1-py3-none-any.whl.metadata
  Downloading tablib-3.6.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\home\anaconda3\lib\site-packages (from requests->cryptocmd) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\home\anaconda3\lib\site-packages (from requests->cryptocmd) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\home\anaconda3\lib\site-packages (from requests->cryptocmd) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\home\anaconda3\lib\site-packages (from requests->cryptocmd) (2023.7.22)
Downloading cryptocmd-0.6.4-py3-none-any.whl (9.1 kB)
Downloading tablib-3.6.1-py3-none-any.whl (47 kB)
   ---------------------------------------- 0.0/47.1 kB ? eta -:--:--
   -------- ------------------------------- 10.2/47.1 kB ? eta -:--:--
   ---------------------------------- ----- 41.0/47.1 kB 388.9 kB/s eta 0:00:01
   ---------------------------------------- 47.1/47.1 kB 391.7 kB/s eta 0:00:00
Installing collected packages: tablib, cryptocmd
Successfully installed cryptocmd-0.6.4 tablib-3.6.1

In [40]:
from cryptocmd import CmcScraper

In [41]:
scraper = CmcScraper('BTC')

dados_cripto = scraper.get_dataframe()

dados_cripto

,Date,Open,High,Low,Close,Volume,Market Cap,Time Open,Time High,Time Low,Time Close
0,2024-04-04,65975.696667,69291.254806,65113.796534,68508.841844,3.443953e+10,1.347932e+12,2024-04-04T00:00:00.000Z,2024-04-04T18:03:00.000Z,2024-04-04T04:24:00.000Z,2024-04-04T23:59:59.999Z
1,2024-04-03,65446.671764,66914.322564,64559.899948,65980.808650,3.448802e+10,1.297904e+12,2024-04-03T00:00:00.000Z,2024-04-03T14:30:00.000Z,2024-04-03T00:39:00.000Z,2024-04-03T23:59:59.999Z
2,2024-04-02,69705.024322,69708.381258,64586.594304,65446.974233,5.070524e+10,1.287439e+12,2024-04-02T00:00:00.000Z,2024-04-02T00:00:00.000Z,2024-04-02T13:34:00.000Z,2024-04-02T23:59:59.999Z
3,2024-04-01,71333.484717,71342.091454,68110.696020,69702.146113,3.487353e+10,1.371141e+12,2024-04-01T00:00:00.000Z,2024-04-01T00:00:00.000Z,2024-04-01T16:01:00.000Z,2024-04-01T23:59:59.999Z
4,2024-03-31,69647.779030,71377.779498,69624.868677,71333.647926,2.005094e+10,1.403108e+12,2024-03-31T00:00:00.000Z,2024-03-31T23:58:00.000Z,2024-03-31T00:01:00.000Z,2024-03-31T23:59:59.999Z
...,...,...,...,...,...,...,...,...,...,...,...
3990,2013-05-02,116.379997,125.599998,92.281898,105.209999,0.000000e+00,1.168517e+09,2013-05-02T00:00:00.000Z,2013-05-02T14:25:01.000Z,2013-05-02T14:30:02.000Z,2013-05-02T23:59:59.999Z
3991,2013-05-01,139.000000,139.889999,107.720001,116.989998,0.000000e+00,1.298955e+09,2013-05-01T00:00:00.000Z,2013-05-01T00:15:01.000Z,2013-05-01T19:55:01.000Z,2013-05-01T23:59:59.999Z
3992,2013-04-30,144.000000,146.929993,134.050003,139.000000,0.000000e+00,1.542813e+09,2013-04-30T00:00:00.000Z,2013-04-30T08:25:02.000Z,2013-04-30T18:55:01.000Z,2013-04-30T23:59:59.999Z
3993,2013-04-29,134.444000,147.488007,134.000000,144.539993,0.000000e+00,1.603769e+09,2013-04-29T00:00:00.000Z,2013-04-29T13:15:01.000Z,2013-04-29T05:20:01.000Z,2013-04-29T23:59:59.999Z
3994,2013-04-28,136.689455,143.365942,110.845593,127.954255,2.595684e+04,1.419008e+09,2013-04-28T00:00:00.000Z,2013-04-28T00:45:00.000Z,2013-04-28T13:05:00.000Z,2013-04-28T23:59:59.999Z

#### Pegando dados do Banco do Brasil via pacote
https://www3.bcb.gov.br/sgspub/localizarseries/localizarSeries.do?method=prepararTelaLocalizarSeries

In [42]:
!pip install python-bcb

Collecting python-bcb
  Obtaining dependency information for python-bcb from https://files.pythonhosted.org/packages/c8/72/0b48869e310869c96d7234ee0b6cb1e64dedd9b987d9e52efbbf25814711/python_bcb-0.2.0-py3-none-any.whl.metadata
  Downloading python_bcb-0.2.0-py3-none-any.whl.metadata (2.5 kB)
Collecting httpx<0.25.0,>=0.24.0 (from python-bcb)
  Obtaining dependency information for httpx<0.25.0,>=0.24.0 from https://files.pythonhosted.org/packages/ec/91/e41f64f03d2a13aee7e8c819d82ee3aa7cdc484d18c0ae859742597d5aa0/httpx-0.24.1-py3-none-any.whl.metadata
  Downloading httpx-0.24.1-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: lxml<5.0.0,>=4.9.2 in c:\users\home\anaconda3\lib\site-packages (from python-bcb) (4.9.3)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in c:\users\home\anaconda3\lib\site-packages (from python-bcb) (2.0.3)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\home\anaconda3\lib\site-packages (from python-bcb) (2.31.0)
Requirement already satisfied: certifi in c:\users\home\anaconda3\lib\site-packages (from httpx<0.25.0,>=0.24.0->python-bcb) (2023.7.22)
Collecting httpcore<0.18.0,>=0.15.0 (from httpx<0.25.0,>=0.24.0->python-bcb)
  Obtaining dependency information for httpcore<0.18.0,>=0.15.0 from https://files.pythonhosted.org/packages/94/2c/2bde7ff8dd2064395555220cbf7cba79991172bf5315a07eb3ac7688d9f1/httpcore-0.17.3-py3-none-any.whl.metadata
  Downloading httpcore-0.17.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: idna in c:\users\home\anaconda3\lib\site-packages (from httpx<0.25.0,>=0.24.0->python-bcb) (3.4)
Requirement already satisfied: sniffio in c:\users\home\anaconda3\lib\site-packages (from httpx<0.25.0,>=0.24.0->python-bcb) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\home\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0.0->python-bcb) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\home\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0.0->python-bcb) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\home\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0.0->python-bcb) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\home\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.0.0->python-bcb) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\home\anaconda3\lib\site-packages (from requests<3.0.0,>=2.31.0->python-bcb) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\home\anaconda3\lib\site-packages (from requests<3.0.0,>=2.31.0->python-bcb) (1.26.16)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\home\anaconda3\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.0->python-bcb) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\home\anaconda3\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx<0.25.0,>=0.24.0->python-bcb) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\home\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->python-bcb) (1.16.0)
Downloading python_bcb-0.2.0-py3-none-any.whl (16 kB)
Downloading httpx-0.24.1-py3-none-any.whl (75 kB)
   ---------------------------------------- 0.0/75.4 kB ? eta -:--:--
   ---------------------------------------- 75.4/75.4 kB 4.1 MB/s eta 0:00:00
Downloading httpcore-0.17.3-py3-none-any.whl (74 kB)
   ---------------------------------------- 0.0/74.5 kB ? eta -:--:--
   ---------------------------------------- 74.5/74.5 kB 4.0 MB/s eta 0:00:00
Installing collected packages: httpcore, httpx, python-bcb
Successfully installed httpcore-0.17.3 httpx-0.24.1 python-bcb-0.2.0

In [43]:
from bcb import sgs

In [45]:
#dados_bc = sgs.get({'DOLAR':1})
dados_bc = sgs.get({'IPCA':433})
dados_bc

            IPCA
Date
1980-01-01  6.62
1980-02-01  4.62
1980-03-01  6.04
1980-04-01  5.29
1980-05-01  5.70
...          ...
2023-10-01  0.24
2023-11-01  0.28
2023-12-01  0.56
2024-01-01  0.42
2024-02-01  0.83

[530 rows x 1 columns]

### Dados coletados via leitura de documentos

In [46]:
dados_shopping = pd.read_csv('shoppings.csv')
dados_shopping

,Shopping,Area por m2,City,State
0,ÁGUAS CLARAS SHOPPING,12626,Brasília,DF
1,ÁGUAS LINDAS SHOPPING,67788,Águas Lindas de Goiás,GO
2,ALAMEDA JUIZ DE FORA,12437,Juiz de Fora,MG
3,ALAMEDA SHOPPING,4807,Brasília,DF
4,ALPHA SQUARE MALL,0,Barueri,SP
...,...,...,...,...
624,VILLAGIO MALL CENTER,5943,Bauru,SP
625,ASSIS PLAZA SHOPPING,1991,Assis,SP
626,MEGA MODA PARK,9920,Goiânia,GO
627,RIVIERA SHOPPING,37393,Bertioga,SP
628,SHOPPING CENTER PACO DO OUVIDOR,2000,Rio de Janeiro,RJ

#### Pib dos municípios

In [47]:
pib_municipios = pd.read_excel('pib_municipios.xlsx')
pib_municipios

                            City        pib
0     Alta Floresta D'Oeste (RO)     734469
1                 Ariquemes (RO)    3209761
2                    Cabixi (RO)     238412
3                    Cacoal (RO)    2792383
4                Cerejeiras (RO)     743037
...                          ...        ...
5565             Vianópolis (GO)     857968
5566         Vicentinópolis (GO)     480173
5567               Vila Boa (GO)     179899
5568          Vila Propício (GO)     308013
5569               Brasília (DF)  286943782

[5570 rows x 2 columns]